[package]
name = "basset"
version = "0.3.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "0.16.0" }
cosmwasm-storage = { version = "1.2.5" }
cosmwasm-std = "1.5.0"
schemars = "0.8.11"
serde = { version = "1.0.147", default-features = false, features = ["derive"] }
cosmwasm-bignumber =  { path = "../bignumber", version = "3.0.0"}

[dev-dependencies]
#cosmwasm-vm = { version = "1.0.0" }
